# 🔄 Pipeline ETL
## Nettoyage et transformation

In [7]:
import sys
sys.path.append('..')
  
import pandas as pd
import glob
import os
from pipeline.cleaner import DataCleaner
from pipeline.transformer import DataTransformer
    
print("✅ Modules importés")

✅ Modules importés

In [8]:
# Charger le dernier fichier brut

csv_files = glob.glob('../data/raw/jobs_*.csv')
if csv_files:
    latest_file = max(csv_files, key=os.path.getctime)
    df_raw = pd.read_csv(latest_file)
    print(f"📁 Fichier chargé: {latest_file}")
    print(f"📊 Dimensions: {df_raw.shape}")
else:
    print("❌ Aucun fichier trouvé")

📁 Fichier chargé: ../data/raw\jobs_20260310_191210.csv
📊 Dimensions: (728, 10)

In [9]:
# Nettoyage

cleaner = DataCleaner()
df_clean = cleaner.clean(df_raw)
df_clean.head()

,url,titre,entreprise,date_publication,region,ville,contrat,experience,niveau_etude,competences_cles
0,https://www.emploi.ma/offre-emploi-maroc/pilot...,Pilote Qualité - Tanger,TESCA MOROCCO,2026-03-04,Tanger-Tétouan-Al Hoceïma,Tanger,CDI,Expérience entre 2 ans et 5 ans,Bac+5 et plus,Qualité - Maintenance - Production - Managemen...
1,https://www.emploi.ma/offre-emploi-maroc/respo...,Responsable Maintenance - Casablanca,BOTTU,2026-02-12,Casablanca-Mohammedia,Casablanca,CDI,Expérience entre 5 ans et 10 ans,Bac+5 et plus,Maintenance - Production - Électromécanique - ...
2,https://www.emploi.ma/offre-emploi-maroc/chef-...,Chef d’Équipe – Installation Photovoltaïque - ...,TECTRA CASA TERTIAIRE – RECRUTEMENT,2026-03-10,Casablanca-Mohammedia,Casablanca,CDI - Intérim,Expérience entre 2 ans et 5 ans - Expérience e...,Bac+2 - Bac+3,Production - Qualité - Maintenance - Montage -...
3,https://www.emploi.ma/offre-emploi-maroc/assis...,Assistant(e) Marketing et Communication - Bous...,SEPALUMIC,2026-02-24,Casablanca-Mohammedia,Bouskoura,CDI,Expérience entre 2 ans et 5 ans,Bac+3,Communication Marketing - Marketing Digital - ...
4,https://www.emploi.ma/offre-emploi-maroc/assis...,Assistante de Direction - Casablanca,GROUPE MCE,2026-02-24,Casablanca-Mohammedia,Casablanca,CDI,Expérience entre 2 ans et 5 ans - Expérience e...,Bac+2 - Bac+3 - Bac+4 - Bac+5 et plus,Assistanat - Support - POWERPOINT - Administra...

In [10]:
# Transformation

transformer = DataTransformer()
df_trans = transformer.transform(df_clean)
df_trans.head()

,url,titre,entreprise,date_publication,region,ville,contrat,experience,niveau_etude,competences_cles,skills_list,experience_cat,annee,mois
0,https://www.emploi.ma/offre-emploi-maroc/pilot...,Pilote Qualité - Tanger,TESCA MOROCCO,2026-03-04,Tanger-Tétouan-Al Hoceïma,Tanger,CDI,Expérience entre 2 ans et 5 ans,Bac+5 et plus,Qualité - Maintenance - Production - Managemen...,"[Qualité, Maintenance, Production, Management ...",Junior (2-5 ans),2026,3
1,https://www.emploi.ma/offre-emploi-maroc/respo...,Responsable Maintenance - Casablanca,BOTTU,2026-02-12,Casablanca-Mohammedia,Casablanca,CDI,Expérience entre 5 ans et 10 ans,Bac+5 et plus,Maintenance - Production - Électromécanique - ...,"[Maintenance, Production, Électromécanique, Ma...",Confirmé (5-10 ans),2026,2
2,https://www.emploi.ma/offre-emploi-maroc/chef-...,Chef d’Équipe – Installation Photovoltaïque - ...,TECTRA CASA TERTIAIRE – RECRUTEMENT,2026-03-10,Casablanca-Mohammedia,Casablanca,CDI - Intérim,Expérience entre 2 ans et 5 ans - Expérience e...,Bac+2 - Bac+3,Production - Qualité - Maintenance - Montage -...,"[Production, Qualité, Maintenance, Montage, Câ...",Junior (2-5 ans),2026,3
3,https://www.emploi.ma/offre-emploi-maroc/assis...,Assistant(e) Marketing et Communication - Bous...,SEPALUMIC,2026-02-24,Casablanca-Mohammedia,Bouskoura,CDI,Expérience entre 2 ans et 5 ans,Bac+3,Communication Marketing - Marketing Digital - ...,"[Communication Marketing, Marketing Digital, S...",Junior (2-5 ans),2026,2
4,https://www.emploi.ma/offre-emploi-maroc/assis...,Assistante de Direction - Casablanca,GROUPE MCE,2026-02-24,Casablanca-Mohammedia,Casablanca,CDI,Expérience entre 2 ans et 5 ans - Expérience e...,Bac+2 - Bac+3 - Bac+4 - Bac+5 et plus,Assistanat - Support - POWERPOINT - Administra...,"[Assistanat, Support, POWERPOINT, Administrati...",Junior (2-5 ans),2026,2

In [11]:
# Sauvegarde

df_trans.to_csv('../data/processed/jobs_clean.csv', index=False)
print(f"✅ Données sauvegardées dans data/processed/jobs_clean.csv")

✅ Données sauvegardées dans data/processed/jobs_clean.csv